services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # mount the current directory to /app in the container, so changes are reflected immediately, no need to rebuild the container
    command: >
      sh -c "python manage.py runserver 0.0.0:8000"